[package]
name = "tinyrenderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
num = "0.4.0"
thiserror = "1.0.30"
anyhow = "1.0.51"
obj-rs = "0.7.0"
glm = "0.2.3"
rand = "0.8.0"